### PR TITLE
Added tokenizer to Qualitivity and Post-Edit Compare; used to calculate accurate word counts through the language platform

### PR DESCRIPTION
**Pull request by Impertatore**

### CODE REVIEW

**Comment by Impertatore** [comment]
Added tokenizer to Qualitivity and Post-Edit Compare; used to calculate accurate word counts through the language platform.

+ Light refactoring:
 - removed the legacy code that was related word counts.
 - naming convention in Terp
 - default: relative location of snk files
 - removed the specific version information declarations for SDL references; Note: we should add the references path info related to the SDL installation folder from project properties.

**Comment by cromica** [comment]
A few remarks:
1. Since the tokenization mechanism is needed in both application. Would it make sense to have it in the [Community Toolkit](https://github.com/sdl/SDL-Studio-Community-Toolkit)? Is this specific to the needs of this 2 plugins or it can be potentially leveraged in other applications too.
2. Make sense to remove the The  Studio API references version, however we need to keep the hint path to the install location in a format like $(ProgramFiles)\SDL\.... . This is important for people cloning the repo to have it compiling immediately.

**Comment by Impertatore** [comment]
Agree, makes sense to move this code related to the tokenization mechanism to the community toolkit; I will make this change and update the PR.
Regarding the hint path, I can put back the project hint details, but it might be cleaner to manage this outside of the project file, especially when we are mapping to different versions.  It is easier to do this with the reference path property of the project; please confirm with the hint path and I will put this back if required.

**Comment by Impertatore** [comment]
closed by mistake

**Comment by Impertatore** [comment]
I have moved the tokenizer project to https://github.com/Impertatore/SDL-Studio-Community-Toolkit, please make reference to the PR https://github.com/sdl/SDL-Studio-Community-Toolkit/pull/2

Once we have the tokenizer project published to nuget, then I will complete this PR referencing the nuget package.  Until then, it is possible to test by compiling the Sdl.Community.Toolkit.Tokenization.dll and copying into yr SDL installation directory.

Note: I have readded $(ProgramFiles) ... in the HintPath declarations as noted in the review comment; you can decide to change this as needed at a later stage.

**Pull request merged**
